# **NumPy is a powerful library for numerical computing**:

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]

[1 2 3 4 5]


# **Performing basic operations on arrays**

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
c = a + b
print(c)  # Output: [5 7 9]

# Element-wise multiplication
d = a * b
print(d)  # Output: [4 10 18]

# Dot product
dot_product = np.dot(a, b)
print(dot_product)  # Output: 32


[5 7 9]
[ 4 10 18]
32


# **Array indexing and slicing**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Accessing individual elements
print(arr[3])  # Output: 1

# Slicing an array
print(arr[1:4])  # Output: [2 3 4]


4
[2 3 4]


# **Reshaping an array**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to a 2x3 matrix
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)
# Output:
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


# **Statistical operations on arrays**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Computing the mean
mean = np.mean(arr)
print(mean)  # Output: 3.0

# Computing the standard deviation
std_dev = np.std(arr)
print(std_dev)  # Output: 1.4142135623730951

# Computing the maximum value
max_val = np.max(arr)
print(max_val)  # Output: 5


3.0
1.4142135623730951
5


# **Array concatenation and stacking**

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenating arrays
concatenated = np.concatenate((a, b))
print(concatenated)
# Output: [1 2 3 4 5 6]

# Stacking arrays vertically
vertical_stack = np.vstack((a, b))
print(vertical_stack)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Stacking arrays horizontally
horizontal_stack = np.hstack((a, b))
print(horizontal_stack)
# Output: [1 2 3 4 5 6]


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# **Random number generation**

In [ ]:
# Generating random integers
random_ints = np.random.randint(low=1, high=10, size=(3, 3))
print(random_ints)

# Generating random floating-point numbers
random_floats = np.random.random(size=(2, 2))
print(random_floats)


[[5 4 3]
 [8 6 2]
 [5 3 3]]
[[0.99413643 0.33552474]
 [0.09797186 0.34850376]]


# **Linear algebra operations**

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Matrix multiplication
matrix_product = np.matmul(a, b)
print(matrix_product)
# Output:
# [[19 22]
#  [43 50]]

# Matrix inverse
inv_a = np.linalg.inv(a)
print(inv_a)
# Output:
# [[-2.   1. ]
#  [ 1.5 -0.5]]

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)


[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# **Creating a matrix from a nested list**

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
# Output:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]


In [ ]:
zeros_matrix = np.zeros((3, 4))
ones_matrix = np.ones((2, 3))
diagonal_matrix = np.diag([1, 2, 3, 4])
random_matrix = np.random.rand(3, 2)
value_matrix = np.full((2, 2), 5)